# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TheoLPP_UI.ui'
#
# Created: Fri Dec 16 16:34:17 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("TheoLPP_Main")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 781, 521))
        self.tabWidget.setObjectName("tabWidget")
        self.theolpp_tab = QtGui.QWidget()
        self.theolpp_tab.setObjectName("theolpp_tab")
        self.gridLayoutWidget_2 = QtGui.QWidget(self.theolpp_tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 752, 461))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.prostane_horizontalLayout = QtGui.QHBoxLayout()
        self.prostane_horizontalLayout.setObjectName("prostane_horizontalLayout")
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.prostane_horizontalLayout.addWidget(self.label_11)
        self.prostane_yes_rb = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.prostane_yes_rb.setChecked(True)
        self.prostane_yes_rb.setAutoExclusive(False)
        self.prostane_yes_rb.setObjectName("prostane_yes_rb")
        self.prostane_horizontalLayout.addWidget(self.prostane_yes_rb)
        self.prostane_no_rb = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.prostane_no_rb.setAutoExclusive(False)
        self.prostane_no_rb.setObjectName("prostane_no_rb")
        self.prostane_horizontalLayout.addWidget(self.prostane_no_rb)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.prostane_horizontalLayout.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.prostane_horizontalLayout, 7, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.max_ox_spb = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.max_ox_spb.setMaximumSize(QtCore.QSize(35, 16777215))
        self.max_ox_spb.setMinimum(1)
        self.max_ox_spb.setMaximum(8)
        self.max_ox_spb.setProperty("value", 3)
        self.max_ox_spb.setObjectName("max_ox_spb")
        self.horizontalLayout.addWidget(self.max_ox_spb)
        spacerItem1 = QtGui.QSpacerItem(108, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.max_keto_lb = QtGui.QLabel(self.gridLayoutWidget_2)
        self.max_keto_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.max_keto_lb.setObjectName("max_keto_lb")
        self.horizontalLayout.addWidget(self.max_keto_lb)
        self.max_keto_spb = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.max_keto_spb.setMaximumSize(QtCore.QSize(35, 16777215))
        self.max_keto_spb.setMaximum(3)
        self.max_keto_spb.setProperty("value", 2)
        self.max_keto_spb.setObjectName("max_keto_spb")
        self.horizontalLayout.addWidget(self.max_keto_spb)
        self.max_ooh_lb = QtGui.QLabel(self.gridLayoutWidget_2)
        self.max_ooh_lb.setMinimumSize(QtCore.QSize(0, 0))
        self.max_ooh_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.max_ooh_lb.setObjectName("max_ooh_lb")
        self.horizontalLayout.addWidget(self.max_ooh_lb)
        self.max_ooh_spb = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.max_ooh_spb.setMaximumSize(QtCore.QSize(35, 16777215))
        self.max_ooh_spb.setMaximum(3)
        self.max_ooh_spb.setProperty("value", 1)
        self.max_ooh_spb.setObjectName("max_ooh_spb")
        self.horizontalLayout.addWidget(self.max_ooh_spb)
        self.max_epoxy_lb = QtGui.QLabel(self.gridLayoutWidget_2)
        self.max_epoxy_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.max_epoxy_lb.setObjectName("max_epoxy_lb")
        self.horizontalLayout.addWidget(self.max_epoxy_lb)
        self.max_epoxy_spb = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.max_epoxy_spb.setMaximumSize(QtCore.QSize(35, 16777215))
        self.max_epoxy_spb.setMaximum(3)
        self.max_epoxy_spb.setObjectName("max_epoxy_spb")
        self.horizontalLayout.addWidget(self.max_epoxy_spb)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 6, 1, 1, 1)
        self.save_msp_pb = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.save_msp_pb.setObjectName("save_msp_pb")
        self.gridLayout_2.addWidget(self.save_msp_pb, 11, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.load_lipid_le = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.load_lipid_le.setObjectName("load_lipid_le")
        self.gridLayout_2.addWidget(self.load_lipid_le, 0, 1, 1, 1)
        self.save_sdf_le = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.save_sdf_le.setObjectName("save_sdf_le")
        self.gridLayout_2.addWidget(self.save_sdf_le, 4, 1, 1, 1)
        self.save_sdf_pb = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.save_sdf_pb.setObjectName("save_sdf_pb")
        self.gridLayout_2.addWidget(self.save_sdf_pb, 4, 2, 1, 1)
        self.excel_horizontalLayout = QtGui.QHBoxLayout()
        self.excel_horizontalLayout.setObjectName("excel_horizontalLayout")
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_14.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_14.setObjectName("label_14")
        self.excel_horizontalLayout.addWidget(self.label_14)
        self.exceltab_cb = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.exceltab_cb.setObjectName("exceltab_cb")
        self.excel_horizontalLayout.addWidget(self.exceltab_cb)
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.excel_horizontalLayout.addItem(spacerItem3)
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_15.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_15.setObjectName("label_15")
        self.excel_horizontalLayout.addWidget(self.label_15)
        self.pl_class_cb = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.pl_class_cb.setObjectName("pl_class_cb")
        self.pl_class_cb.addItem("")
        self.pl_class_cb.addItem("")
        self.pl_class_cb.addItem("")
        self.pl_class_cb.addItem("")
        self.pl_class_cb.addItem("")
        self.pl_class_cb.addItem("")
        self.excel_horizontalLayout.addWidget(self.pl_class_cb)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.excel_horizontalLayout.addItem(spacerItem4)
        self.gridLayout_2.addLayout(self.excel_horizontalLayout, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.oxlevel_horizontalLayout = QtGui.QHBoxLayout()
        self.oxlevel_horizontalLayout.setObjectName("oxlevel_horizontalLayout")
        self.ox_level1_rb = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.ox_level1_rb.setChecked(True)
        self.ox_level1_rb.setAutoExclusive(False)
        self.ox_level1_rb.setObjectName("ox_level1_rb")
        self.oxlevel_horizontalLayout.addWidget(self.ox_level1_rb)
        self.ox_level2_rb = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.ox_level2_rb.setAutoExclusive(False)
        self.ox_level2_rb.setObjectName("ox_level2_rb")
        self.oxlevel_horizontalLayout.addWidget(self.ox_level2_rb)
        self.ox_level3_rb = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.ox_level3_rb.setAutoExclusive(False)
        self.ox_level3_rb.setObjectName("ox_level3_rb")
        self.oxlevel_horizontalLayout.addWidget(self.ox_level3_rb)
        spacerItem5 = QtGui.QSpacerItem(62, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.oxlevel_horizontalLayout.addItem(spacerItem5)
        self.oap_chb = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.oap_chb.setChecked(True)
        self.oap_chb.setObjectName("oap_chb")
        self.oxlevel_horizontalLayout.addWidget(self.oap_chb)
        self.ocp_chb = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.ocp_chb.setChecked(True)
        self.ocp_chb.setObjectName("ocp_chb")
        self.oxlevel_horizontalLayout.addWidget(self.ocp_chb)
        self.lyso_oap_chb = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.lyso_oap_chb.setChecked(True)
        self.lyso_oap_chb.setObjectName("lyso_oap_chb")
        self.oxlevel_horizontalLayout.addWidget(self.lyso_oap_chb)
        self.lyso_ocp_chb = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.lyso_ocp_chb.setChecked(True)
        self.lyso_ocp_chb.setObjectName("lyso_ocp_chb")
        self.oxlevel_horizontalLayout.addWidget(self.lyso_ocp_chb)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.oxlevel_horizontalLayout.addItem(spacerItem6)
        self.gridLayout_2.addLayout(self.oxlevel_horizontalLayout, 5, 1, 1, 1)
        self.msp_horizontalLayout = QtGui.QHBoxLayout()
        self.msp_horizontalLayout.setObjectName("msp_horizontalLayout")
        self.save_msp_lb = QtGui.QLabel(self.gridLayoutWidget_2)
        self.save_msp_lb.setObjectName("save_msp_lb")
        self.msp_horizontalLayout.addWidget(self.save_msp_lb)
        self.save_msp_le = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.save_msp_le.setObjectName("save_msp_le")
        self.msp_horizontalLayout.addWidget(self.save_msp_le)
        self.gridLayout_2.addLayout(self.msp_horizontalLayout, 11, 1, 1, 1)
        self.run_status_te = QtGui.QTextEdit(self.gridLayoutWidget_2)
        self.run_status_te.setObjectName("run_status_te")
        self.gridLayout_2.addWidget(self.run_status_te, 13, 1, 1, 1)
        self.load_lipid_pb = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.load_lipid_pb.setObjectName("load_lipid_pb")
        self.gridLayout_2.addWidget(self.load_lipid_pb, 0, 2, 1, 1)
        self.run_theolpp_pb = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.run_theolpp_pb.setObjectName("run_theolpp_pb")
        self.gridLayout_2.addWidget(self.run_theolpp_pb, 13, 0, 1, 1)
        self.spectra_horizontalLayout = QtGui.QHBoxLayout()
        self.spectra_horizontalLayout.setObjectName("spectra_horizontalLayout")
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.spectra_horizontalLayout.addWidget(self.label_9)
        self.spectra_yes_rb = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.spectra_yes_rb.setChecked(True)
        self.spectra_yes_rb.setAutoExclusive(False)
        self.spectra_yes_rb.setObjectName("spectra_yes_rb")
        self.spectra_horizontalLayout.addWidget(self.spectra_yes_rb)
        self.spectra_no_rb = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.spectra_no_rb.setAutoExclusive(False)
        self.spectra_no_rb.setObjectName("spectra_no_rb")
        self.spectra_horizontalLayout.addWidget(self.spectra_no_rb)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.spectra_horizontalLayout.addItem(spacerItem7)
        self.gridLayout_2.addLayout(self.spectra_horizontalLayout, 10, 1, 1, 1)
        self.prostane_ox_horizontalLayout = QtGui.QHBoxLayout()
        self.prostane_ox_horizontalLayout.setObjectName("prostane_ox_horizontalLayout")
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.prostane_ox_horizontalLayout.addWidget(self.label_12)
        self.prostane_ox_yes_rb = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.prostane_ox_yes_rb.setCheckable(False)
        self.prostane_ox_yes_rb.setAutoExclusive(False)
        self.prostane_ox_yes_rb.setObjectName("prostane_ox_yes_rb")
        self.prostane_ox_horizontalLayout.addWidget(self.prostane_ox_yes_rb)
        self.prostane_ox_no_rb = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.prostane_ox_no_rb.setChecked(True)
        self.prostane_ox_no_rb.setAutoExclusive(False)
        self.prostane_ox_no_rb.setObjectName("prostane_ox_no_rb")
        self.prostane_ox_horizontalLayout.addWidget(self.prostane_ox_no_rb)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.prostane_ox_horizontalLayout.addItem(spacerItem8)
        self.gridLayout_2.addLayout(self.prostane_ox_horizontalLayout, 8, 1, 1, 1)
        self.line_8 = QtGui.QFrame(self.gridLayoutWidget_2)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_2.addWidget(self.line_8, 3, 1, 1, 1)
        self.line_7 = QtGui.QFrame(self.gridLayoutWidget_2)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_2.addWidget(self.line_7, 9, 1, 1, 1)
        self.line_6 = QtGui.QFrame(self.gridLayoutWidget_2)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 12, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 5, 0, 1, 1)
        self.tabWidget.addTab(self.theolpp_tab, "")
        self.cfg_tab = QtGui.QWidget()
        self.cfg_tab.setObjectName("cfg_tab")
        self.gridLayoutWidget = QtGui.QWidget(self.cfg_tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 751, 231))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frag_pattern_pb = QtGui.QPushButton(self.gridLayoutWidget)
        self.frag_pattern_pb.setObjectName("frag_pattern_pb")
        self.gridLayout.addWidget(self.frag_pattern_pb, 5, 2, 1, 1)
        self.mod_lst__pb = QtGui.QPushButton(self.gridLayoutWidget)
        self.mod_lst__pb.setObjectName("mod_lst__pb")
        self.gridLayout.addWidget(self.mod_lst__pb, 0, 2, 1, 1)
        self.fa_lst_pb = QtGui.QPushButton(self.gridLayoutWidget)
        self.fa_lst_pb.setObjectName("fa_lst_pb")
        self.gridLayout.addWidget(self.fa_lst_pb, 1, 2, 1, 1)
        self.prostane_mod_lst_pb = QtGui.QPushButton(self.gridLayoutWidget)
        self.prostane_mod_lst_pb.setObjectName("prostane_mod_lst_pb")
        self.gridLayout.addWidget(self.prostane_mod_lst_pb, 2, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.frag_pattern_le = QtGui.QLineEdit(self.gridLayoutWidget)
        self.frag_pattern_le.setObjectName("frag_pattern_le")
        self.gridLayout.addWidget(self.frag_pattern_le, 5, 1, 1, 1)
        self.mod_lst_le = QtGui.QLineEdit(self.gridLayoutWidget)
        self.mod_lst_le.setObjectName("mod_lst_le")
        self.gridLayout.addWidget(self.mod_lst_le, 0, 1, 1, 1)
        self.prostane_mod_lst_le = QtGui.QLineEdit(self.gridLayoutWidget)
        self.prostane_mod_lst_le.setObjectName("prostane_mod_lst_le")
        self.gridLayout.addWidget(self.prostane_mod_lst_le, 2, 1, 1, 1)
        self.fa_lst_le = QtGui.QLineEdit(self.gridLayoutWidget)
        self.fa_lst_le.setObjectName("fa_lst_le")
        self.gridLayout.addWidget(self.fa_lst_le, 1, 1, 1, 1)
        self.set_default_pb = QtGui.QPushButton(self.gridLayoutWidget)
        self.set_default_pb.setObjectName("set_default_pb")
        self.gridLayout.addWidget(self.set_default_pb, 6, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 3, 0, 1, 1)
        self.prostane_abbr_lst_le = QtGui.QLineEdit(self.gridLayoutWidget)
        self.prostane_abbr_lst_le.setObjectName("prostane_abbr_lst_le")
        self.gridLayout.addWidget(self.prostane_abbr_lst_le, 3, 1, 1, 1)
        self.prostane_abbr_lst_pb = QtGui.QPushButton(self.gridLayoutWidget)
        self.prostane_abbr_lst_pb.setObjectName("prostane_abbr_lst_pb")
        self.gridLayout.addWidget(self.prostane_abbr_lst_pb, 3, 2, 1, 1)
        self.line_9 = QtGui.QFrame(self.gridLayoutWidget)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 4, 1, 1, 1)
        self.tabWidget.addTab(self.cfg_tab, "")
        self.generator_tab = QtGui.QWidget()
        self.generator_tab.setObjectName("generator_tab")
        self.line = QtGui.QFrame(self.generator_tab)
        self.line.setGeometry(QtCore.QRect(500, 20, 16, 291))
        self.line.setFrameShadow(QtGui.QFrame.Plain)
        self.line.setLineWidth(4)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_3 = QtGui.QFrame(self.generator_tab)
        self.line_3.setGeometry(QtCore.QRect(470, 170, 41, 20))
        self.line_3.setFrameShadow(QtGui.QFrame.Plain)
        self.line_3.setLineWidth(4)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtGui.QFrame(self.generator_tab)
        self.line_4.setGeometry(QtCore.QRect(470, 10, 41, 20))
        self.line_4.setFrameShadow(QtGui.QFrame.Plain)
        self.line_4.setLineWidth(4)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtGui.QFrame(self.generator_tab)
        self.line_5.setGeometry(QtCore.QRect(510, 300, 41, 20))
        self.line_5.setFrameShadow(QtGui.QFrame.Plain)
        self.line_5.setLineWidth(4)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.pl_class2_cb = QtGui.QComboBox(self.generator_tab)
        self.pl_class2_cb.setGeometry(QtCore.QRect(550, 300, 197, 20))
        self.pl_class2_cb.setObjectName("pl_class2_cb")
        self.pl_class2_cb.addItem("")
        self.pl_class2_cb.addItem("")
        self.pl_class2_cb.addItem("")
        self.pl_class2_cb.addItem("")
        self.pl_class2_cb.addItem("")
        self.pl_class2_cb.addItem("")
        self.gridLayoutWidget_3 = QtGui.QWidget(self.generator_tab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 340, 751, 121))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 0, 1, 1)
        self.run_fa_list_pte = QtGui.QPlainTextEdit(self.gridLayoutWidget_3)
        self.run_fa_list_pte.setObjectName("run_fa_list_pte")
        self.gridLayout_3.addWidget(self.run_fa_list_pte, 1, 1, 1, 1)
        self.save_fa_list_le = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.save_fa_list_le.setObjectName("save_fa_list_le")
        self.gridLayout_3.addWidget(self.save_fa_list_le, 0, 1, 1, 1)
        self.save_fa_list_pb = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.save_fa_list_pb.setObjectName("save_fa_list_pb")
        self.gridLayout_3.addWidget(self.save_fa_list_pb, 0, 2, 1, 1)
        self.run_fa_list_pb = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.run_fa_list_pb.setObjectName("run_fa_list_pb")
        self.gridLayout_3.addWidget(self.run_fa_list_pb, 1, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.generator_tab)
        self.label_16.setGeometry(QtCore.QRect(470, 160, 31, 20))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtGui.QLabel(self.generator_tab)
        self.label_17.setGeometry(QtCore.QRect(470, 0, 31, 20))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtGui.QLabel(self.generator_tab)
        self.label_18.setGeometry(QtCore.QRect(520, 290, 31, 20))
        self.label_18.setObjectName("label_18")
        self.gridLayoutWidget_4 = QtGui.QWidget(self.generator_tab)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 451, 134))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.sn1_20_5_chb = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sn1_20_5_chb.setObjectName("sn1_20_5_chb")
        self.gridLayout_4.addWidget(self.sn1_20_5_chb, 2, 3, 1, 1)
        self.sn1_22_5_chb = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sn1_22_5_chb.setObjectName("sn1_22_5_chb")
        self.gridLayout_4.addWidget(self.sn1_22_5_chb, 3, 2, 1, 1)
        self.sn1_22_6_chb = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sn1_22_6_chb.setObjectName("sn1_22_6_chb")
        self.gridLayout_4.addWidget(self.sn1_22_6_chb, 3, 3, 1, 1)
        self.sn1_20_0_chb = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sn1_20_0_chb.setObjectName("sn1_20_0_chb")
        self.gridLayout_4.addWidget(self.sn1_20_0_chb, 0, 3, 1, 1)
        self.sn1_20_3_chb = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sn1_20_3_chb.setObjectName("sn1_20_3_chb")
        self.gridLayout_4.addWidget(self.sn1_20_3_chb, 2, 1, 1, 1)
        self.sn1_16_0_chb = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sn1_16_0_chb.setObjectName("sn1_16_0_chb")
        self.gridLayout_4.addWidget(self.sn1_16_0_chb, 0, 1, 1, 1)
        self.sn1_18_1_chb = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sn1_18_1_chb.setObjectName("sn1_18_1_chb")
        self.gridLayout_4.addWidget(self.sn1_18_1_chb, 1, 1, 1, 1)
        self.sn1_o_16_0_chb = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sn1_o_16_0_chb.setObjectName("sn1_o_16_0_chb")
        self.gridLayout_4.addWidget(self.sn1_o_16_0_chb, 4, 0, 1, 1)
        self.sn1_22_3_chb = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sn1_22_3_chb.setObjectName("sn1_22_3_chb")
        self.gridLayout_4.addWidget(self.sn1_22_3_chb, 3, 0, 1, 1)
        self.sn1_22_4_chb = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sn1_22_4_chb.setObjectName("sn1_22_4_chb")
        self.gridLayout_4.addWidget(self.sn1_22_4_chb, 3, 1, 1, 1)
        self.sn1_o_18_0_chb = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sn1_o_18_0_chb.setObjectName("sn1_o_18_0_chb")
        self.gridLayout_4.addWidget(self.sn1_o_18_0_chb, 4, 1, 1, 1)
        self.sn1_14_0_chb = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sn1_14_0_chb.setObjectName("sn1_14_0_chb")
        self.gridLayout_4.addWidget(self.sn1_14_0_chb, 0, 0, 1, 1)
        self.sn1_20_4_chb = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sn1_20_4_chb.setObjectName("sn1_20_4_chb")
        self.gridLayout_4.addWidget(self.sn1_20_4_chb, 2, 2, 1, 1)
        self.sn1_20_2_chb = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sn1_20_2_chb.setObjectName("sn1_20_2_chb")
        self.gridLayout_4.addWidget(self.sn1_20_2_chb, 2, 0, 1, 1)
        self.sn1_18_3_chb = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sn1_18_3_chb.setObjectName("sn1_18_3_chb")
        self.gridLayout_4.addWidget(self.sn1_18_3_chb, 1, 3, 1, 1)
        self.sn1_o_20_0_chb = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sn1_o_20_0_chb.setObjectName("sn1_o_20_0_chb")
        self.gridLayout_4.addWidget(self.sn1_o_20_0_chb, 4, 2, 1, 1)
        self.sn1_18_2_chb = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sn1_18_2_chb.setObjectName("sn1_18_2_chb")
        self.gridLayout_4.addWidget(self.sn1_18_2_chb, 1, 2, 1, 1)
        self.sn1_18_0_chb = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sn1_18_0_chb.setObjectName("sn1_18_0_chb")
        self.gridLayout_4.addWidget(self.sn1_18_0_chb, 0, 2, 1, 1)
        self.sn1_16_1_chb = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sn1_16_1_chb.setObjectName("sn1_16_1_chb")
        self.gridLayout_4.addWidget(self.sn1_16_1_chb, 1, 0, 1, 1)
        self.sn1_p_16_0_chb = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sn1_p_16_0_chb.setObjectName("sn1_p_16_0_chb")
        self.gridLayout_4.addWidget(self.sn1_p_16_0_chb, 5, 0, 1, 1)
        self.sn1_p_18_0_chb = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sn1_p_18_0_chb.setObjectName("sn1_p_18_0_chb")
        self.gridLayout_4.addWidget(self.sn1_p_18_0_chb, 5, 1, 1, 1)
        self.sn1_p_20_0_chb = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sn1_p_20_0_chb.setObjectName("sn1_p_20_0_chb")
        self.gridLayout_4.addWidget(self.sn1_p_20_0_chb, 5, 2, 1, 1)
        self.sn1_fa_all_chb = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.sn1_fa_all_chb.setObjectName("sn1_fa_all_chb")
        self.gridLayout_4.addWidget(self.sn1_fa_all_chb, 5, 3, 1, 1)
        self.gridLayoutWidget_5 = QtGui.QWidget(self.generator_tab)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 180, 451, 134))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.sn2_20_5_chb = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.sn2_20_5_chb.setObjectName("sn2_20_5_chb")
        self.gridLayout_5.addWidget(self.sn2_20_5_chb, 2, 3, 1, 1)
        self.sn2_22_5_chb = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.sn2_22_5_chb.setObjectName("sn2_22_5_chb")
        self.gridLayout_5.addWidget(self.sn2_22_5_chb, 3, 2, 1, 1)
        self.sn2_22_6_chb = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.sn2_22_6_chb.setObjectName("sn2_22_6_chb")
        self.gridLayout_5.addWidget(self.sn2_22_6_chb, 3, 3, 1, 1)
        self.sn2_20_0_chb = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.sn2_20_0_chb.setObjectName("sn2_20_0_chb")
        self.gridLayout_5.addWidget(self.sn2_20_0_chb, 0, 3, 1, 1)
        self.sn2_20_3_chb = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.sn2_20_3_chb.setObjectName("sn2_20_3_chb")
        self.gridLayout_5.addWidget(self.sn2_20_3_chb, 2, 1, 1, 1)
        self.sn2_16_0_chb = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.sn2_16_0_chb.setObjectName("sn2_16_0_chb")
        self.gridLayout_5.addWidget(self.sn2_16_0_chb, 0, 1, 1, 1)
        self.sn2_18_1_chb = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.sn2_18_1_chb.setObjectName("sn2_18_1_chb")
        self.gridLayout_5.addWidget(self.sn2_18_1_chb, 1, 1, 1, 1)
        self.sn2_o_16_0_chb = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.sn2_o_16_0_chb.setObjectName("sn2_o_16_0_chb")
        self.gridLayout_5.addWidget(self.sn2_o_16_0_chb, 4, 0, 1, 1)
        self.sn2_22_3_chb = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.sn2_22_3_chb.setObjectName("sn2_22_3_chb")
        self.gridLayout_5.addWidget(self.sn2_22_3_chb, 3, 0, 1, 1)
        self.sn2_22_4_chb = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.sn2_22_4_chb.setObjectName("sn2_22_4_chb")
        self.gridLayout_5.addWidget(self.sn2_22_4_chb, 3, 1, 1, 1)
        self.sn2_o_18_0_chb = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.sn2_o_18_0_chb.setObjectName("sn2_o_18_0_chb")
        self.gridLayout_5.addWidget(self.sn2_o_18_0_chb, 4, 1, 1, 1)
        self.sn2_14_0_chb = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.sn2_14_0_chb.setObjectName("sn2_14_0_chb")
        self.gridLayout_5.addWidget(self.sn2_14_0_chb, 0, 0, 1, 1)
        self.sn2_20_4_chb = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.sn2_20_4_chb.setObjectName("sn2_20_4_chb")
        self.gridLayout_5.addWidget(self.sn2_20_4_chb, 2, 2, 1, 1)
        self.sn2_20_2_chb = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.sn2_20_2_chb.setObjectName("sn2_20_2_chb")
        self.gridLayout_5.addWidget(self.sn2_20_2_chb, 2, 0, 1, 1)
        self.sn2_18_3_chb = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.sn2_18_3_chb.setObjectName("sn2_18_3_chb")
        self.gridLayout_5.addWidget(self.sn2_18_3_chb, 1, 3, 1, 1)
        self.sn2_o_20_0_chb = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.sn2_o_20_0_chb.setObjectName("sn2_o_20_0_chb")
        self.gridLayout_5.addWidget(self.sn2_o_20_0_chb, 4, 2, 1, 1)
        self.sn2_18_2_chb = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.sn2_18_2_chb.setObjectName("sn2_18_2_chb")
        self.gridLayout_5.addWidget(self.sn2_18_2_chb, 1, 2, 1, 1)
        self.sn2_18_0_chb = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.sn2_18_0_chb.setObjectName("sn2_18_0_chb")
        self.gridLayout_5.addWidget(self.sn2_18_0_chb, 0, 2, 1, 1)
        self.sn2_16_1_chb = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.sn2_16_1_chb.setObjectName("sn2_16_1_chb")
        self.gridLayout_5.addWidget(self.sn2_16_1_chb, 1, 0, 1, 1)
        self.sn2_p_16_0_chb = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.sn2_p_16_0_chb.setObjectName("sn2_p_16_0_chb")
        self.gridLayout_5.addWidget(self.sn2_p_16_0_chb, 5, 0, 1, 1)
        self.sn2_p_18_0_chb = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.sn2_p_18_0_chb.setObjectName("sn2_p_18_0_chb")
        self.gridLayout_5.addWidget(self.sn2_p_18_0_chb, 5, 1, 1, 1)
        self.sn2_p_20_0_chb = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.sn2_p_20_0_chb.setObjectName("sn2_p_20_0_chb")
        self.gridLayout_5.addWidget(self.sn2_p_20_0_chb, 5, 2, 1, 1)
        self.sn2_fa_all_chb = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.sn2_fa_all_chb.setObjectName("sn2_fa_all_chb")
        self.gridLayout_5.addWidget(self.sn2_fa_all_chb, 5, 3, 1, 1)
        self.line_2 = QtGui.QFrame(self.generator_tab)
        self.line_2.setGeometry(QtCore.QRect(10, 160, 451, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.tabWidget.addTab(self.generator_tab, "")
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(10, 540, 461, 16))
        self.label_19.setTextFormat(QtCore.Qt.RichText)
        self.label_19.setObjectName("label_19")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.pl_class_cb.setCurrentIndex(1)
        self.pl_class2_cb.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("TheoLPP_Main", "TheoLPP_Main", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("TheoLPP_Main", "Prostanes:", None, QtGui.QApplication.UnicodeUTF8))
        self.prostane_yes_rb.setText(QtGui.QApplication.translate("TheoLPP_Main", "Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.prostane_no_rb.setText(QtGui.QApplication.translate("TheoLPP_Main", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("TheoLPP_Main", "Max # of mod sites:", None, QtGui.QApplication.UnicodeUTF8))
        self.max_keto_lb.setText(QtGui.QApplication.translate("TheoLPP_Main", "Max Keto:", None, QtGui.QApplication.UnicodeUTF8))
        self.max_ooh_lb.setText(QtGui.QApplication.translate("TheoLPP_Main", "Max OOH:", None, QtGui.QApplication.UnicodeUTF8))
        self.max_epoxy_lb.setText(QtGui.QApplication.translate("TheoLPP_Main", "Max Epoxy:", None, QtGui.QApplication.UnicodeUTF8))
        self.save_msp_pb.setText(QtGui.QApplication.translate("TheoLPP_Main", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("TheoLPP_Main", "Save .sdf as", None, QtGui.QApplication.UnicodeUTF8))
        self.save_sdf_pb.setText(QtGui.QApplication.translate("TheoLPP_Main", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("TheoLPP_Main", "Excel tab:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("TheoLPP_Main", "Lipid class:", None, QtGui.QApplication.UnicodeUTF8))
        self.pl_class_cb.setItemText(0, QtGui.QApplication.translate("TheoLPP_Main", "Phosphatidic acid (PA)", None, QtGui.QApplication.UnicodeUTF8))
        self.pl_class_cb.setItemText(1, QtGui.QApplication.translate("TheoLPP_Main", "Phosphatidylcholine (PC)", None, QtGui.QApplication.UnicodeUTF8))
        self.pl_class_cb.setItemText(2, QtGui.QApplication.translate("TheoLPP_Main", "Phosphatidylethanolamine (PE)", None, QtGui.QApplication.UnicodeUTF8))
        self.pl_class_cb.setItemText(3, QtGui.QApplication.translate("TheoLPP_Main", "Phosphatidylglycerol (PG)", None, QtGui.QApplication.UnicodeUTF8))
        self.pl_class_cb.setItemText(4, QtGui.QApplication.translate("TheoLPP_Main", "Phosphatidylinositol (PI)", None, QtGui.QApplication.UnicodeUTF8))
        self.pl_class_cb.setItemText(5, QtGui.QApplication.translate("TheoLPP_Main", "Phosphatidylserine (PS)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("TheoLPP_Main", "Load lipids table", None, QtGui.QApplication.UnicodeUTF8))
        self.ox_level1_rb.setText(QtGui.QApplication.translate("TheoLPP_Main", "Level 1", None, QtGui.QApplication.UnicodeUTF8))
        self.ox_level2_rb.setText(QtGui.QApplication.translate("TheoLPP_Main", "Level 2", None, QtGui.QApplication.UnicodeUTF8))
        self.ox_level3_rb.setText(QtGui.QApplication.translate("TheoLPP_Main", "Level 3", None, QtGui.QApplication.UnicodeUTF8))
        self.oap_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "OAP", None, QtGui.QApplication.UnicodeUTF8))
        self.ocp_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "OCP", None, QtGui.QApplication.UnicodeUTF8))
        self.lyso_oap_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "Lyso OAP", None, QtGui.QApplication.UnicodeUTF8))
        self.lyso_ocp_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "Lyso OCP", None, QtGui.QApplication.UnicodeUTF8))
        self.save_msp_lb.setText(QtGui.QApplication.translate("TheoLPP_Main", "Save .msp spectra", None, QtGui.QApplication.UnicodeUTF8))
        self.load_lipid_pb.setText(QtGui.QApplication.translate("TheoLPP_Main", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.run_theolpp_pb.setText(QtGui.QApplication.translate("TheoLPP_Main", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("TheoLPP_Main", "Create in-silico spectra:", None, QtGui.QApplication.UnicodeUTF8))
        self.spectra_yes_rb.setText(QtGui.QApplication.translate("TheoLPP_Main", "Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.spectra_no_rb.setText(QtGui.QApplication.translate("TheoLPP_Main", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("TheoLPP_Main", "Prostane side chain oxidation:", None, QtGui.QApplication.UnicodeUTF8))
        self.prostane_ox_yes_rb.setText(QtGui.QApplication.translate("TheoLPP_Main", "Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.prostane_ox_no_rb.setText(QtGui.QApplication.translate("TheoLPP_Main", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("TheoLPP_Main", "Oxidation level:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.theolpp_tab), QtGui.QApplication.translate("TheoLPP_Main", "TheoLPP", None, QtGui.QApplication.UnicodeUTF8))
        self.frag_pattern_pb.setText(QtGui.QApplication.translate("TheoLPP_Main", "open", None, QtGui.QApplication.UnicodeUTF8))
        self.mod_lst__pb.setText(QtGui.QApplication.translate("TheoLPP_Main", "open", None, QtGui.QApplication.UnicodeUTF8))
        self.fa_lst_pb.setText(QtGui.QApplication.translate("TheoLPP_Main", "open", None, QtGui.QApplication.UnicodeUTF8))
        self.prostane_mod_lst_pb.setText(QtGui.QApplication.translate("TheoLPP_Main", "open", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("TheoLPP_Main", "Fragmentation patterns: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("TheoLPP_Main", "General modification list: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("TheoLPP_Main", "Fatty acids white list: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("TheoLPP_Main", "Prostane mod settings: ", None, QtGui.QApplication.UnicodeUTF8))
        self.set_default_pb.setText(QtGui.QApplication.translate("TheoLPP_Main", "Save above settings as defaullt", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("TheoLPP_Main", "Prostane abbrevations", None, QtGui.QApplication.UnicodeUTF8))
        self.prostane_abbr_lst_pb.setText(QtGui.QApplication.translate("TheoLPP_Main", "open", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cfg_tab), QtGui.QApplication.translate("TheoLPP_Main", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.pl_class2_cb.setItemText(0, QtGui.QApplication.translate("TheoLPP_Main", "Phosphatidic acid (PA)", None, QtGui.QApplication.UnicodeUTF8))
        self.pl_class2_cb.setItemText(1, QtGui.QApplication.translate("TheoLPP_Main", "Phosphatidylcholine (PC)", None, QtGui.QApplication.UnicodeUTF8))
        self.pl_class2_cb.setItemText(2, QtGui.QApplication.translate("TheoLPP_Main", "Phosphatidylethanolamine (PE)", None, QtGui.QApplication.UnicodeUTF8))
        self.pl_class2_cb.setItemText(3, QtGui.QApplication.translate("TheoLPP_Main", "Phosphatidylglycerol (PG)", None, QtGui.QApplication.UnicodeUTF8))
        self.pl_class2_cb.setItemText(4, QtGui.QApplication.translate("TheoLPP_Main", "Phosphatidylinositol (PI)", None, QtGui.QApplication.UnicodeUTF8))
        self.pl_class2_cb.setItemText(5, QtGui.QApplication.translate("TheoLPP_Main", "Phosphatidylserine (PS)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("TheoLPP_Main", "Save to:", None, QtGui.QApplication.UnicodeUTF8))
        self.save_fa_list_pb.setText(QtGui.QApplication.translate("TheoLPP_Main", "Save as", None, QtGui.QApplication.UnicodeUTF8))
        self.run_fa_list_pb.setText(QtGui.QApplication.translate("TheoLPP_Main", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("TheoLPP_Main", "sn 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("TheoLPP_Main", "sn 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("TheoLPP_Main", "HG", None, QtGui.QApplication.UnicodeUTF8))
        self.sn1_20_5_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "20:5", None, QtGui.QApplication.UnicodeUTF8))
        self.sn1_22_5_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "22:5", None, QtGui.QApplication.UnicodeUTF8))
        self.sn1_22_6_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "22:6", None, QtGui.QApplication.UnicodeUTF8))
        self.sn1_20_0_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "20:0", None, QtGui.QApplication.UnicodeUTF8))
        self.sn1_20_3_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "20:3", None, QtGui.QApplication.UnicodeUTF8))
        self.sn1_16_0_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "16:0", None, QtGui.QApplication.UnicodeUTF8))
        self.sn1_18_1_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "18:1", None, QtGui.QApplication.UnicodeUTF8))
        self.sn1_o_16_0_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "O-16:0", None, QtGui.QApplication.UnicodeUTF8))
        self.sn1_22_3_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "22:3", None, QtGui.QApplication.UnicodeUTF8))
        self.sn1_22_4_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "22:4", None, QtGui.QApplication.UnicodeUTF8))
        self.sn1_o_18_0_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "O-18:0", None, QtGui.QApplication.UnicodeUTF8))
        self.sn1_14_0_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "14:0", None, QtGui.QApplication.UnicodeUTF8))
        self.sn1_20_4_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "20:4", None, QtGui.QApplication.UnicodeUTF8))
        self.sn1_20_2_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "20:2", None, QtGui.QApplication.UnicodeUTF8))
        self.sn1_18_3_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "18:3", None, QtGui.QApplication.UnicodeUTF8))
        self.sn1_o_20_0_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "O-20:0", None, QtGui.QApplication.UnicodeUTF8))
        self.sn1_18_2_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "18:2", None, QtGui.QApplication.UnicodeUTF8))
        self.sn1_18_0_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "18:0", None, QtGui.QApplication.UnicodeUTF8))
        self.sn1_16_1_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "16:1", None, QtGui.QApplication.UnicodeUTF8))
        self.sn1_p_16_0_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "P-16:0", None, QtGui.QApplication.UnicodeUTF8))
        self.sn1_p_18_0_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "P-18:0", None, QtGui.QApplication.UnicodeUTF8))
        self.sn1_p_20_0_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "P-20:0", None, QtGui.QApplication.UnicodeUTF8))
        self.sn1_fa_all_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "Select all", None, QtGui.QApplication.UnicodeUTF8))
        self.sn2_20_5_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "20:5", None, QtGui.QApplication.UnicodeUTF8))
        self.sn2_22_5_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "22:5", None, QtGui.QApplication.UnicodeUTF8))
        self.sn2_22_6_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "22:6", None, QtGui.QApplication.UnicodeUTF8))
        self.sn2_20_0_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "20:0", None, QtGui.QApplication.UnicodeUTF8))
        self.sn2_20_3_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "20:3", None, QtGui.QApplication.UnicodeUTF8))
        self.sn2_16_0_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "16:0", None, QtGui.QApplication.UnicodeUTF8))
        self.sn2_18_1_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "18:1", None, QtGui.QApplication.UnicodeUTF8))
        self.sn2_o_16_0_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "O-16:0", None, QtGui.QApplication.UnicodeUTF8))
        self.sn2_22_3_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "22:3", None, QtGui.QApplication.UnicodeUTF8))
        self.sn2_22_4_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "22:4", None, QtGui.QApplication.UnicodeUTF8))
        self.sn2_o_18_0_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "O-18:0", None, QtGui.QApplication.UnicodeUTF8))
        self.sn2_14_0_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "14:0", None, QtGui.QApplication.UnicodeUTF8))
        self.sn2_20_4_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "20:4", None, QtGui.QApplication.UnicodeUTF8))
        self.sn2_20_2_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "20:2", None, QtGui.QApplication.UnicodeUTF8))
        self.sn2_18_3_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "18:3", None, QtGui.QApplication.UnicodeUTF8))
        self.sn2_o_20_0_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "O-20:0", None, QtGui.QApplication.UnicodeUTF8))
        self.sn2_18_2_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "18:2", None, QtGui.QApplication.UnicodeUTF8))
        self.sn2_18_0_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "18:0", None, QtGui.QApplication.UnicodeUTF8))
        self.sn2_16_1_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "16:1", None, QtGui.QApplication.UnicodeUTF8))
        self.sn2_p_16_0_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "P-16:0", None, QtGui.QApplication.UnicodeUTF8))
        self.sn2_p_18_0_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "P-18:0", None, QtGui.QApplication.UnicodeUTF8))
        self.sn2_p_20_0_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "P-20:0", None, QtGui.QApplication.UnicodeUTF8))
        self.sn2_fa_all_chb.setText(QtGui.QApplication.translate("TheoLPP_Main", "Select all", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.generator_tab), QtGui.QApplication.translate("TheoLPP_Main", "FA List Generator", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("TheoLPP_Main", "<html><head/><body><p>Project LPPdb @ <a href=\"http://www.zv.uni-leipzig.de/\"><span style=\" text-decoration: underline; color:#0000ff;\">University of Leipzig</span></a> | <a href=\"http://research.uni-leipzig.de/bioanalytik/index.html\"><span style=\" text-decoration: underline; color:#0000ff;\">AG Bioanalytik</span></a> | <a href=\"https://home.uni-leipzig.de/fedorova/\"><span style=\" text-decoration: underline; color:#0000ff;\">Fedorova research group</span></a> | 2016-2017</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))

